### ISSUE TITLE
Repo contains no files for esx_advancedfuel

### ISSUE THREAD

**Issue by hyp3rstrike** [HumanTree92/esx_advancedfuel#4]
**Repo contains no files for esx_advancedfuel by HumanTree92**

**Questions**
Have you made changes to anything in `client/main.lua` or `server/main.lua`?: n/a
Have you looked through the Closed Topics?: n/a
Have you looked through the Wiki?: n/a
Are you using a Pre-Installed ESX? If Yes who?: No
Are you using es_extended? If Yes what Version? (Example: 1.2): Final
Are you using Essentialmode?: Yes
Are you using ExtendedMode?: No
Are you using OneSync?: Yes
Linux or Windows?: Linux

**Comment by HumanTree92** [comment]
Your dumb get blocked
